name: Deploy Documentation

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - '.github/workflows/docs.yml'
      - 'README.md'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name "Trieu Nguyen Hai"
          git config user.email "55079705+trieuntu@users.noreply.github.com"
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install dependencies
        run: pip install mkdocs-material
      - name: Build and deploy
        run: mkdocs gh-deploy --force
